# frozen_string_literal: true

module AppDefaults
  MAGIC_LINK_TTL_MINUTES = 15

  CHECKIN_DEFAULT_INTERVAL_HOURS = 168
  CHECKIN_DEFAULT_GRACE_HOURS = 72
  CHECKIN_DEFAULT_COOLDOWN_HOURS = 48
  CHECKIN_MIN_INTERVAL_HOURS = 1
  CHECKIN_MIN_GRACE_HOURS = 1
  CHECKIN_MIN_COOLDOWN_HOURS = 1
  CHECKIN_MAX_INTERVAL_HOURS = 8_760
  CHECKIN_MAX_GRACE_HOURS = 8_760
  CHECKIN_MAX_COOLDOWN_HOURS = 8_760

  RATE_LIMIT_MAGIC_LINK_PER_IP = 5
  RATE_LIMIT_MAGIC_LINK_PERIOD = 300

  ARGON2ID_OPS_LIMIT = 3
  ARGON2ID_MEM_LIMIT = 268_435_456

  INVITE_TOKEN_TTL_DAYS = 7

  TRUSTED_CONTACT_DEFAULT_PING_INTERVAL_HOURS = 24
  TRUSTED_CONTACT_DEFAULT_PAUSE_DURATION_HOURS = 168
  TRUSTED_CONTACT_MIN_PING_INTERVAL_HOURS = 1
  TRUSTED_CONTACT_MAX_PING_INTERVAL_HOURS = 8_760
  TRUSTED_CONTACT_MIN_PAUSE_DURATION_HOURS = 1
  TRUSTED_CONTACT_MAX_PAUSE_DURATION_HOURS = 8_760
  TRUSTED_CONTACT_TOKEN_TTL_HOURS = 168

  CSP_REPORT_ONLY = false
end
